# -*- coding: utf-8 -*-
"""Globals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ma438JEEW08CMDjnE1q8RicG-W2y4lUf
"""

import os
import torch

# Paths
data_root = '/content/silkworm_dataset/silk_dataset'
csv_path  = os.path.join(data_root, '0_data.csv')
best_model_path   = 'models/best_mobilenet.pth'
pruned_model_path = 'models/pruned_mobilenet.pth'

# Hyperparameters
batch_size   = 32
lr           = 1e-4
weight_decay = 1e-4
num_classes  = 2
input_size   = (224, 224)
max_epochs   = 20
patience     = 2
prune_amounts = [0.0, 0.1, 0.2]
device       = torch.device('cuda' if torch.cuda.is_available() else 'cpu')