# -*- coding: utf-8 -*-
"""Mobilenet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ma438JEEW08CMDjnE1q8RicG-W2y4lUf
"""

import torch
import torch.nn as nn
import torchvision

from globals import num_classes, device

# Pretrained MobileNetV2 with custom classifier
def get_mobilenet():
    model = torchvision.models.mobilenet_v2(weights=torchvision.models.MobileNet_V2_Weights.IMAGENET1K_V1)
    model.classifier[1] = nn.Linear(model.last_channel, num_classes)
    return model.to(device)